<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="uncal-proc-tecnicos.aspx.cs" Inherits="WebApplication2.html.uncal_proc_tecnicos" %>
<asp:Content ID="HeaderContent" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
<h2>Proc Tecnicos Calibraciones</h2>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO002-01 Calibracion en el Laboratorio.pdf" target="_blank">Procedimiento de Calibración en el Laboratorio</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO020-01 Intercomparacion Interlaboratorio.pdf" target="_blank">Procedimiento de Intercomparación Interlaboratorio</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO021-01 Calibracion de termometros.pdf" target="_blank">Procedimiento de calibración de Micrómetros externos, internos y de profundidad</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO022-01 Calibracion de balanzas.pdf" target="_blank">Procedimiento de calibración de Balanzas Electrónicas</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO023-01 Calibracion de diales indicadores.pdf" target="_blank">Procedimiento de calibración de Diales Indicadores</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO024-01 Calibracion de pies de metro.pdf" target="_blank">Procedimiento de calibración de Pies de Metro</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO025-01 Calculo de incertidumbre.pdf" target="_blank">Procedimiento de cálculo de Incertidumbre</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO026-01 Calibracion de medidores e indicadores de presion.pdf" target="_blank">Procedimiento de calibración de Medidores/ indicadores de presión Hidráulicas y Neumáticas</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO027-01 Control ambiental para calibraciones.pdf" target="_blank">Procedimiento de Control Ambiental para Calibraciones</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO028-01 Calibracion en Terreno.pdf" target="_blank">Procedimiento de Calibración en Terreno</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO030-01 Preparación de equipos para calibración..pdf" target="_blank">Procedimiento de Preparación de Equipos para la Calibración</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO040-01 Calibracion de Termometros.pdf" target="_blank">Procedimiento de Calibración de Termómetros de líquido en vidrio</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO047-01 Calibracion de transductores de presion.pdf" target="_blank">Calibración de Transductores de Presión.</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO048-01 Calibracion de instalaciones termicas.pdf" target="_blank">Calibración de Instalaciones Térmicas</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO049-01 Mantencion de Patrones.pdf" target="_blank">Procedimiento de Mantención de Patrones </a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO050-01 Mantencion de humedad relativa.pdf" target="_blank">Mantención de humedad relativa</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO053-01 Calibracion de medidores o generadores de PH.pdf" target="_blank">Procedimiento de Calibración de medidores Generadores de PH</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO054-01 Calibracion de electrodos de PH.pdf" target="_blank">Procedimiento de calibración de electrodos de PH</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO056-01 Calibracion medidor de velocidad con GPS.pdf" target="_blank">Calibración del equipo medidor de velocidad con GPS</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO057-01 Calibracion del equipo medidor de velocidad.pdf" target="_blank">Calibración del Equipo medidor de velocidad</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO059-01 Calibracion Termo-higrometro y Termo-higrografo.pdf" target="_blank">Procedimiento de Calibración de Termo-higrómetro y Termo-higrógrafo.</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO080-01 Trabajo calibracion no conforme.pdf" target="_blank">Trabajo de calibración no-conforme</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO083-01 Calibración sensores e indicadores de temperatura por señal eléctrica..pdf" target="_blank">Procedimiento de calibración de sensores de temperatura e indicadores de temperatura por simulación de señal eléctrica.</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO109-01 Calibracion de sistemas de temperatura digitales o analogos.pdf" target="_blank">Procedimiento de calibraciones de  sistemas de temperatura con indicadores digitales análogos</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO115-01 Intercomparaciones en el laboratorio de calibraciones.pdf" target="_blank">Procedimiento de intercomparaciones en el laboratorio de calibraciones</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO117-01 Validacion de metodos de la magnitud temperatura.pdf" target="_blank">Validación de métodos de calibración de la magnitud temperatura</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO123-01 Calibracion de Wattmetros.pdf" target="_blank">Calibración de wattmetros</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO127-01 Calibracion de termometros infrarrojo.pdf" target="_blank">Calibración de Termómetros Infrarrojo</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO129-01 Sistema de Calibracion Automatico para instrumentos electronicos .pdf" target="_blank">Sistema de Calibración Automático y Semiautomático para Instrumentos Electrónicos</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO130-01 Calibracion de Multimetros Fluke 87III 87IV 87 V 177 y 179.pdf" target="_blank">Calibración de Multímetros marca FLUKE, modelos 87III, 87IV, 87V, 177 y 179</a></p>
<p><a href="file:///\\Spool2\SitioWebGC\SitioWebCalidad\uncalibracionesdocs\procedimientos\tecnicos\6752PRO131-01 Calibracion Generador de Señales Wavetek 39A.pdf" target="_blank">Calibración de Generador de Señales marca Wavetek 39A</a></p>
</asp:Content>
